// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcpzrkikgelpmqzdzxww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcHpya2lrZ2VscG1xemR6eHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDE1MDgsImV4cCI6MjA2OTQ3NzUwOH0.o2I251FQ-569O_YNbtVZZcT3MSQCAFmkVhP70c-cL-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});